### PR TITLE
Changed WinResult to WindowsError, and added usage of std::result::Re…

### PR DESCRIPTION
**Pull request by aweinstock314**
…sult where necessary.

### CODE REVIEW

**Comment by DoumanAsh** [comment]
Hm... not sure how i feel about it, but let me think about it a bit.

**Comment by DoumanAsh** [comment]
I'm not entirely sure if ```Result``` is actually needed here also.
I admit that my approach may be... a bit wanky but i don't really see much difference with built-in ```Result```

**Comment by DoumanAsh** [comment]
After looking into your code again i generally don't see any issues but:
```Result<(), WindowsError>``` For me it seems to be more easier just return ```WindowsError``` directly. But i would like to know what is benefit for ```Result``` abstraction? Is it more idiomatic?

**Comment by aweinstock314** [comment]
Just returning `WindowsError` is incorrect (since there may not be an error). `Result<(), WindowsError>` allows `Ok(())` to be used in the case where there is no error. Previously, you were using `WinResult(0)`, which is the idiomatic way to handle that case in C, but not in Rust (and has the same drawbacks it does in C, like making it easier to accidentally not check the return code). Using `Result` is Rust-idiomatic, and also allows the caller conveniences like the `try!` macro.

**Comment by DoumanAsh** [comment]
Ok. I will re-check your commit again and will merge it.
After that i'll verify builds by myself and will make some adjustments to general style.

I suppose there is nothing to do about NBC. I'm not really good with library things...
Anyway thank you for correction for this crate

**Pull request merged**
