### PR TITLE
feat: support setting formats without clear

### PR DESCRIPTION
**Pull request by fufesou**
We really need to set the pasteboard without clearing the previous content sometimes.

Such as when setting multiple formats at the same time.

### CODE REVIEW

**Comment by DoumanAsh** [comment]
I'm actually not sure if not emptied clipboard is good approach format for every case, but I can imagine use case for that.
So it can be useful customization point indeed

**Comment by DoumanAsh** [comment]
I added API in a more generic manner for every function except `set` because for some reason there was just separate function to customize this behavior 😫 
https://github.com/DoumanAsh/clipboard-win/commit/d8cfd073ad245697e0834ba85626f23376ce65f3

I believe there is no issue except in case of string behavior is unclear due to multiple formats being compatible with string therefore making it possible to have multiple formats present even though you set unicode string

I will release it as 5.4.0 unless you have other conerns

**Comment by fufesou** [comment]
The new API looks great and is easy to use.

**Comment by DoumanAsh** [comment]
I've release 5.4.0 version

**Pull request closed without merging**
